add_test( [==[AxonCache version]==] /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=AxonCache version]==])
set_tests_properties( [==[AxonCache version]==] PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( BucketCacheTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=BucketCacheTest]==])
set_tests_properties( BucketCacheTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheFactoryTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheFactoryTest]==])
set_tests_properties( CacheFactoryTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheFileBuilderTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheFileBuilderTest]==])
set_tests_properties( CacheFileBuilderTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheFileWriterTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheFileWriterTest]==])
set_tests_properties( CacheFileWriterTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheHeaderTestToString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheHeaderTestToString]==])
set_tests_properties( CacheHeaderTestToString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheReaderCApiBasicTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheReaderCApiBasicTest]==])
set_tests_properties( CacheReaderCApiBasicTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheReaderCApiTypedValueTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheReaderCApiTypedValueTest]==])
set_tests_properties( CacheReaderCApiTypedValueTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueConsumerNoneTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueConsumerNoneTest]==])
set_tests_properties( CacheValueConsumerNoneTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueConsumerTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueConsumerTest]==])
set_tests_properties( CacheValueConsumerTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserEmptyLine /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserEmptyLine]==])
set_tests_properties( CacheValueParserEmptyLine PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserEmptyLines /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserEmptyLines]==])
set_tests_properties( CacheValueParserEmptyLines PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserEmptyValue /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserEmptyValue]==])
set_tests_properties( CacheValueParserEmptyValue PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserInvalidKeyPair /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserInvalidKeyPair]==])
set_tests_properties( CacheValueParserInvalidKeyPair PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserSingleLine /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserSingleLine]==])
set_tests_properties( CacheValueParserSingleLine PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVector /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVector]==])
set_tests_properties( CacheValueParserVector PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVectorAllEmptyValues /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVectorAllEmptyValues]==])
set_tests_properties( CacheValueParserVectorAllEmptyValues PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVectorEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVectorEmpty]==])
set_tests_properties( CacheValueParserVectorEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVectorSingleValue /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVectorSingleValue]==])
set_tests_properties( CacheValueParserVectorSingleValue PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVectorSomeEmptyValues /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVectorSomeEmptyValues]==])
set_tests_properties( CacheValueParserVectorSomeEmptyValues PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueParserVectorSorting /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueParserVectorSorting]==])
set_tests_properties( CacheValueParserVectorSorting PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueTestEqualityCheck /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueTestEqualityCheck]==])
set_tests_properties( CacheValueTestEqualityCheck PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueTestKeyValuePair /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueTestKeyValuePair]==])
set_tests_properties( CacheValueTestKeyValuePair PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueTestStringList /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueTestStringList]==])
set_tests_properties( CacheValueTestStringList PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueTestStringType /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueTestStringType]==])
set_tests_properties( CacheValueTestStringType PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheValueTestTypeToString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheValueTestTypeToString]==])
set_tests_properties( CacheValueTestTypeToString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheWriterCApiBasicTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheWriterCApiBasicTest]==])
set_tests_properties( CacheWriterCApiBasicTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( CacheWriterCApiOffsetBitsTooSmallTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=CacheWriterCApiOffsetBitsTooSmallTest]==])
set_tests_properties( CacheWriterCApiOffsetBitsTooSmallTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestCollisions /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestCollisions]==])
set_tests_properties( ChainedValueTestCollisions PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestEmptyKey /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestEmptyKey]==])
set_tests_properties( ChainedValueTestEmptyKey PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestEmptyKeyValue /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestEmptyKeyValue]==])
set_tests_properties( ChainedValueTestEmptyKeyValue PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestEmptyValue /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestEmptyValue]==])
set_tests_properties( ChainedValueTestEmptyValue PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestMany /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestMany]==])
set_tests_properties( ChainedValueTestMany PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestSimple /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestSimple]==])
set_tests_properties( ChainedValueTestSimple PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( ChainedValueTestTypeMismatch /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=ChainedValueTestTypeMismatch]==])
set_tests_properties( ChainedValueTestTypeMismatch PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( DataFileReaderTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=DataFileReaderTest]==])
set_tests_properties( DataFileReaderTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( GenerateCacheFromFileAndVerify /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=GenerateCacheFromFileAndVerify]==])
set_tests_properties( GenerateCacheFromFileAndVerify PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( GenerateHeaderLongNameTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=GenerateHeaderLongNameTest]==])
set_tests_properties( GenerateHeaderLongNameTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( GenerateHeaderTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=GenerateHeaderTest]==])
set_tests_properties( GenerateHeaderTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( GenerateHeaderTestReadMalformed /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=GenerateHeaderTestReadMalformed]==])
set_tests_properties( GenerateHeaderTestReadMalformed PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( GenerateHeaderTestReadShort /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=GenerateHeaderTestReadShort]==])
set_tests_properties( GenerateHeaderTestReadShort PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTest]==])
set_tests_properties( HashedCacheBaseTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestGetDoesNotExist /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestGetDoesNotExist]==])
set_tests_properties( HashedCacheBaseTestGetDoesNotExist PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestGetEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestGetEmpty]==])
set_tests_properties( HashedCacheBaseTestGetEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestGetLongVector /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestGetLongVector]==])
set_tests_properties( HashedCacheBaseTestGetLongVector PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestGetVector /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestGetVector]==])
set_tests_properties( HashedCacheBaseTestGetVector PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestKeyAndValueTooLarge /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestKeyAndValueTooLarge]==])
set_tests_properties( HashedCacheBaseTestKeyAndValueTooLarge PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestNumberOfKeySlots /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestNumberOfKeySlots]==])
set_tests_properties( HashedCacheBaseTestNumberOfKeySlots PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestOutput /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestOutput]==])
set_tests_properties( HashedCacheBaseTestOutput PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestPutDuplicateKeys /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestPutDuplicateKeys]==])
set_tests_properties( HashedCacheBaseTestPutDuplicateKeys PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( HashedCacheBaseTestType /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=HashedCacheBaseTestType]==])
set_tests_properties( HashedCacheBaseTestType PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheAllTypeTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheAllTypeTest]==])
set_tests_properties( LinearProbeCacheAllTypeTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheAllTypeToStringTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheAllTypeToStringTest]==])
set_tests_properties( LinearProbeCacheAllTypeToStringTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseKeySpaceisFull /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseKeySpaceisFull]==])
set_tests_properties( LinearProbeCacheBaseKeySpaceisFull PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseLoadFactorTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseLoadFactorTest]==])
set_tests_properties( LinearProbeCacheBaseLoadFactorTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTest]==])
set_tests_properties( LinearProbeCacheBaseTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestGetDoesNotExist /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestGetDoesNotExist]==])
set_tests_properties( LinearProbeCacheBaseTestGetDoesNotExist PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestGetEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestGetEmpty]==])
set_tests_properties( LinearProbeCacheBaseTestGetEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestGetVector /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestGetVector]==])
set_tests_properties( LinearProbeCacheBaseTestGetVector PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestGetVectorKeyspaceFull /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestGetVectorKeyspaceFull]==])
set_tests_properties( LinearProbeCacheBaseTestGetVectorKeyspaceFull PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestOutput /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestOutput]==])
set_tests_properties( LinearProbeCacheBaseTestOutput PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestPutDuplicateKeys /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestPutDuplicateKeys]==])
set_tests_properties( LinearProbeCacheBaseTestPutDuplicateKeys PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBaseTestType /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBaseTestType]==])
set_tests_properties( LinearProbeCacheBaseTestType PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheBigOffsetTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheBigOffsetTest]==])
set_tests_properties( LinearProbeCacheBigOffsetTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheDefaultValueReturnTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheDefaultValueReturnTest]==])
set_tests_properties( LinearProbeCacheDefaultValueReturnTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs16Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs16Test]==])
set_tests_properties( LinearProbeCacheOfs16Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs28Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs28Test]==])
set_tests_properties( LinearProbeCacheOfs28Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs31Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs31Test]==])
set_tests_properties( LinearProbeCacheOfs31Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs32Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs32Test]==])
set_tests_properties( LinearProbeCacheOfs32Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs34Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs34Test]==])
set_tests_properties( LinearProbeCacheOfs34Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCacheOfs35Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCacheOfs35Test]==])
set_tests_properties( LinearProbeCacheOfs35Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeCachePutAPItest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeCachePutAPItest]==])
set_tests_properties( LinearProbeCachePutAPItest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeDedupCacheOfs28Test /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeDedupCacheOfs28Test]==])
set_tests_properties( LinearProbeDedupCacheOfs28Test PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeDedupSetDuplicatedValues /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeDedupSetDuplicatedValues]==])
set_tests_properties( LinearProbeDedupSetDuplicatedValues PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeForwardIncompatibility /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeForwardIncompatibility]==])
set_tests_properties( LinearProbeForwardIncompatibility PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestBitMasks /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestBitMasks]==])
set_tests_properties( LinearProbeTestBitMasks PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestGetLongVector28Bits /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestGetLongVector28Bits]==])
set_tests_properties( LinearProbeTestGetLongVector28Bits PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestGetLongVector35Bits /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestGetLongVector35Bits]==])
set_tests_properties( LinearProbeTestGetLongVector35Bits PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestInvalidOffsetBits /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestInvalidOffsetBits]==])
set_tests_properties( LinearProbeTestInvalidOffsetBits PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestKeyAndValueTooLarge /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestKeyAndValueTooLarge]==])
set_tests_properties( LinearProbeTestKeyAndValueTooLarge PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestLog2OfKeyWidth /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestLog2OfKeyWidth]==])
set_tests_properties( LinearProbeTestLog2OfKeyWidth PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestOffsetBitsTooShort /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestOffsetBitsTooShort]==])
set_tests_properties( LinearProbeTestOffsetBitsTooShort PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestRoundPow2 /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestRoundPow2]==])
set_tests_properties( LinearProbeTestRoundPow2 PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LinearProbeTestRoundPow2 /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LinearProbeTestRoundPow2]==])
set_tests_properties( LinearProbeTestRoundPow2 PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( LoadCacheFromTmpAndVerify /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=LoadCacheFromTmpAndVerify]==])
set_tests_properties( LoadCacheFromTmpAndVerify PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MallocMemoryHandlerTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MallocMemoryHandlerTest]==])
set_tests_properties( MallocMemoryHandlerTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTest]==])
set_tests_properties( MapCacheBaseTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestGetDoesNotExist /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestGetDoesNotExist]==])
set_tests_properties( MapCacheBaseTestGetDoesNotExist PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestGetEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestGetEmpty]==])
set_tests_properties( MapCacheBaseTestGetEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestGetVector /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestGetVector]==])
set_tests_properties( MapCacheBaseTestGetVector PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestNumberOfKeySlots /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestNumberOfKeySlots]==])
set_tests_properties( MapCacheBaseTestNumberOfKeySlots PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestOutput /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestOutput]==])
set_tests_properties( MapCacheBaseTestOutput PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestPutDuplicateKeys /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestPutDuplicateKeys]==])
set_tests_properties( MapCacheBaseTestPutDuplicateKeys PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MapCacheBaseTestType /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MapCacheBaseTestType]==])
set_tests_properties( MapCacheBaseTestType PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( MmapMemoryHandlerTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=MmapMemoryHandlerTest]==])
set_tests_properties( MmapMemoryHandlerTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( SimpleProbeTestLog2OfKeyWidth /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=SimpleProbeTestLog2OfKeyWidth]==])
set_tests_properties( SimpleProbeTestLog2OfKeyWidth PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( SimpleProbeTestRoundPow2 /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=SimpleProbeTestRoundPow2]==])
set_tests_properties( SimpleProbeTestRoundPow2 PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringEmpty]==])
set_tests_properties( StringListToStringToStringEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringEmptyString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringEmptyString]==])
set_tests_properties( StringListToStringToStringEmptyString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringMulti /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringMulti]==])
set_tests_properties( StringListToStringToStringMulti PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringOvermaxLength /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringOvermaxLength]==])
set_tests_properties( StringListToStringToStringOvermaxLength PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringSingle /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringSingle]==])
set_tests_properties( StringListToStringToStringSingle PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringSomeEmptyString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringSomeEmptyString]==])
set_tests_properties( StringListToStringToStringSomeEmptyString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToStringSomeEmptyStringAtEnd /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToStringSomeEmptyStringAtEnd]==])
set_tests_properties( StringListToStringToStringSomeEmptyStringAtEnd PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorEmpty /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorEmpty]==])
set_tests_properties( StringListToStringToVectorEmpty PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorEmptyString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorEmptyString]==])
set_tests_properties( StringListToStringToVectorEmptyString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorMulti /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorMulti]==])
set_tests_properties( StringListToStringToVectorMulti PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorSingle /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorSingle]==])
set_tests_properties( StringListToStringToVectorSingle PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorSomeEmptyString /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorSomeEmptyString]==])
set_tests_properties( StringListToStringToVectorSomeEmptyString PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( StringListToStringToVectorSomeEmptyStringAtEnd /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=StringListToStringToVectorSomeEmptyStringAtEnd]==])
set_tests_properties( StringListToStringToVectorSomeEmptyStringAtEnd PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
add_test( TypeToStringTest /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test/axoncacheTest [==[--test-case=TypeToStringTest]==])
set_tests_properties( TypeToStringTest PROPERTIES WORKING_DIRECTORY /Users/erolkeskiner/Playground/bidderserver-bazelification/AxonCache/cmake-build/test LABELS)
set( axoncacheTest_TESTS [==[AxonCache version]==] BucketCacheTest CacheFactoryTest CacheFileBuilderTest CacheFileWriterTest CacheHeaderTestToString CacheReaderCApiBasicTest CacheReaderCApiTypedValueTest CacheValueConsumerNoneTest CacheValueConsumerTest CacheValueParserEmptyLine CacheValueParserEmptyLines CacheValueParserEmptyValue CacheValueParserInvalidKeyPair CacheValueParserSingleLine CacheValueParserVector CacheValueParserVectorAllEmptyValues CacheValueParserVectorEmpty CacheValueParserVectorSingleValue CacheValueParserVectorSomeEmptyValues CacheValueParserVectorSorting CacheValueTestEqualityCheck CacheValueTestKeyValuePair CacheValueTestStringList CacheValueTestStringType CacheValueTestTypeToString CacheWriterCApiBasicTest CacheWriterCApiOffsetBitsTooSmallTest ChainedValueTestCollisions ChainedValueTestEmptyKey ChainedValueTestEmptyKeyValue ChainedValueTestEmptyValue ChainedValueTestMany ChainedValueTestSimple ChainedValueTestTypeMismatch DataFileReaderTest GenerateCacheFromFileAndVerify GenerateHeaderLongNameTest GenerateHeaderTest GenerateHeaderTestReadMalformed GenerateHeaderTestReadShort HashedCacheBaseTest HashedCacheBaseTestGetDoesNotExist HashedCacheBaseTestGetEmpty HashedCacheBaseTestGetLongVector HashedCacheBaseTestGetVector HashedCacheBaseTestKeyAndValueTooLarge HashedCacheBaseTestNumberOfKeySlots HashedCacheBaseTestOutput HashedCacheBaseTestPutDuplicateKeys HashedCacheBaseTestType LinearProbeCacheAllTypeTest LinearProbeCacheAllTypeToStringTest LinearProbeCacheBaseKeySpaceisFull LinearProbeCacheBaseLoadFactorTest LinearProbeCacheBaseTest LinearProbeCacheBaseTestGetDoesNotExist LinearProbeCacheBaseTestGetEmpty LinearProbeCacheBaseTestGetVector LinearProbeCacheBaseTestGetVectorKeyspaceFull LinearProbeCacheBaseTestOutput LinearProbeCacheBaseTestPutDuplicateKeys LinearProbeCacheBaseTestType LinearProbeCacheBigOffsetTest LinearProbeCacheDefaultValueReturnTest LinearProbeCacheOfs16Test LinearProbeCacheOfs28Test LinearProbeCacheOfs31Test LinearProbeCacheOfs32Test LinearProbeCacheOfs34Test LinearProbeCacheOfs35Test LinearProbeCachePutAPItest LinearProbeDedupCacheOfs28Test LinearProbeDedupSetDuplicatedValues LinearProbeForwardIncompatibility LinearProbeTestBitMasks LinearProbeTestGetLongVector28Bits LinearProbeTestGetLongVector35Bits LinearProbeTestInvalidOffsetBits LinearProbeTestKeyAndValueTooLarge LinearProbeTestLog2OfKeyWidth LinearProbeTestOffsetBitsTooShort LinearProbeTestRoundPow2 LinearProbeTestRoundPow2 LoadCacheFromTmpAndVerify MallocMemoryHandlerTest MapCacheBaseTest MapCacheBaseTestGetDoesNotExist MapCacheBaseTestGetEmpty MapCacheBaseTestGetVector MapCacheBaseTestNumberOfKeySlots MapCacheBaseTestOutput MapCacheBaseTestPutDuplicateKeys MapCacheBaseTestType MmapMemoryHandlerTest SimpleProbeTestLog2OfKeyWidth SimpleProbeTestRoundPow2 StringListToStringToStringEmpty StringListToStringToStringEmptyString StringListToStringToStringMulti StringListToStringToStringOvermaxLength StringListToStringToStringSingle StringListToStringToStringSomeEmptyString StringListToStringToStringSomeEmptyStringAtEnd StringListToStringToVectorEmpty StringListToStringToVectorEmptyString StringListToStringToVectorMulti StringListToStringToVectorSingle StringListToStringToVectorSomeEmptyString StringListToStringToVectorSomeEmptyStringAtEnd TypeToStringTest)
