name: Go formatter

on:
  pull_request:
    branches: [ master ]   # CI on PRs targeting master
  push:
    branches: [ master ]   # CI on merge commits to master only

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'   # pick your Go version

      - name: Check formatting
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files are not gofmt'ed:"
            echo "$unformatted"
            echo "Run 'gofmt -w .' locally to fix"
            exit 1
          fi
