name: Rust module integration test

on:
  pull_request:
    branches: [ master ]   # CI on PRs targeting master
  push:
    branches: [ master ]   # CI on merge commits to master only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build Rust crate
        run: cargo build --verbose

      - name: Test Rust crate
        run: cargo test --all --verbose

